### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by doublesy** [easy-wx/wx-mp-svr#1]
请问下既然通过pip install wx-mp-svr引入了依赖，为什么还单独建立了一个模块？
![image](https://github.com/easy-wx/wx-mp-svr/assets/43924702/d9f9eeb6-8538-44d1-81df-145c4fde1889)

**Comment by panzhongxian** [comment]
@doublesy 这个仓库就 pip install wx-mp-svr 中 "wx-mp-svr" 项目的源代码哈
